# Generated by Django 2.0.3 on 2018-03-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusersocialauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUserSocialAuth',
        ),
    ]
